# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches:
      - dev

jobs:
  deploy-dev:
    # if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Deploy NodeJS App to Production Server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: root
          script: |
            cd /mnt/toucher/toucher-backend
            echo ${{secrets.SSH_HOST}}
            echo ${{secrets.SSH_KEY}}
            git pull origin dev
            npm install
            npm run build
            pm2 restart apis-toucher
          debug: true
